config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home', to: 'pages#home', as: :home
  get 'projects', to: 'pages#projects'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Kristina Zhizherina | Personal website </title>
    <meta name="description" content="Junior Front End Developer."/>
    <meta property="og:image" content="/images/christin-hume-mfB1B1s4sMc-unsplash.jpg"/> <!--Photo by Christin Hume on Unsplash-->
    <meta property="og:image:width" content="300" />
    <meta property="og:image:height" content="200" />
    <%= favicon_link_tag asset_path('/images/logo-white.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar.html' %>
    <%= yield %>
    <%= render 'shared/footer.html' %>
  </body>
</html>

app/views/pages/home.html.erb
<section class="banner-area" id="home">
  <div class="container"> 
    <div class = "row justify-content-start align-items-center">
      <div class="col-lg-6 col-md-12 no-padding banner-right">
        <%= image_tag(("profile-picture.jpg"), class: "img-fluid", alt: "Kristina's picture") %>
      </div>
      <div class="col-lg-6 col-md-12 banner-left">
        <h1 class="banner-text">
          Hi, I'm  <br>
          <span>Kristina Zhizherina</span> <br>
          Junior Front End Developer
        </h1>
      </div>
    </div>
  </div><!--#container-->
</section><!--#banner-area-->
    
<section class="info-area" id="info">
  <div class="container info-text">
    <div class="row">
      <div class="col-lg-6">
        <div class="welcome-text">
          <h2>About myself</h2>
          <div>
            <img class="rocket-img" src="rocket-img.png" alt="Rocket image" copyright="Icon made by Flat Icons from www.flaticon.com"/>
            <p>
            Passionate and extremely motivated Junior Front end developer eager to learn and create something new every day.</p>
          </div>
          <hr>
          <div> 
            <img class="team-img" src="team-img.png" alt="Team image" copyright="Icon made by Flat Icons from www.flaticon.com">
            <p>Productive and effective either way if it is a team-play or independent work.</p>
          </div>
          <hr>
          <div>
            <img class="webdesign-img" src="webdesign-img.png" alt="Web-design image" copyright="Icon made by Freepik from www.flaticon.com">
            <p>Keen to build or clone sites that will be optimized to load fast, responsive, and a pleasure to use.</p>
          </div>
          <hr>
          <div>
            <img class="competence-img" src="competence-img.png" alt="Competence image" copyright="Icon made by Flat Icons from www.flaticon.com">
            <p>4 years of customer communication, adaptability, and time-management solid experiences in a huge car company.</p>
          </div>  
          <hr>
        </div>
      </div><!--col-lg-6-->
      <div class="col-lg-6">
        <div class="tools">
          <h2>Skills</h2>
          <p><a href="http://w3schools-fa.ir/html/html_intro.html" target="_blank">HTML5</a> &
            <a href="https://www.w3schools.com/css/default.asp" target="_blank">CSS3</a>
          </p>
          <div class="skill-container">
            <div class="skills html-css">80%</div>
          </div>
          <p>
            <a href="https://www.w3schools.com/js/default.asp" target="_blank">JavaScript</a>
            <a href="https://www.w3schools.com/js/js_es6.asp" target="_blank">(ES6) </a> &
            <a href="https://reactjs.org/" target="_blank">React</a>
          </p>
          <div class="skill-container">
            <div class="skills js">60%</div>
          </div>
          <p>
            <a href="https://www.ruby-lang.org/en/about/" target="_blank">Ruby</a>
            <a href="https://rubyonrails.org/" target="_blank">(RoR)</a>
          </p>
          <div class="skill-container">
            <div class="skills ruby">50%</div>
          </div>
          <p> 
            <a href="https://sass-lang.com/" target="_blank">SASS</a>
          </p>
          <div class="skill-container">
            <div class="skills sass">70%</div>
          </div>
           <p> 
            <a href="https://getbootstrap.com/" target="_blank">Bootstrap</a>
          </p>
          <div class="skill-container">
            <div class="skills bootstrap">70%</div>
          </div>
          <p><a href="https://git-scm.com/" target="_blank">Git</a></p>
          <div class="skill-container">
            <div class="skills git">80%</div>
          </div>
          
        </div><!--#tools-->
      </div><!--col-lg-6-->
    </div>
  </div>
</section><!--#info-area-->

<section class="third-section">
  <div class="container qualifications">
    <div class="row">
      <div class="col-lg-6 col-sm-6">
        <div>
          <h2>Work History</h2>
          <div class="single-box">
            <h3>Customer Service Specialist</h3>
            <p>March 2016 - January 2020</p>
            <h4>Avis Budget</h4>
          </div>
          <div class="single-box">
            <h3>Volunteer</h3>
            <p>May 2013</p>
            <h4>SportAccord</h4>
          </div>
            <div class="single-box">
            <h3>Volunteer</h3>
            <p>June - July 2012</p>
            <h4>UNESCO</h4>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-sm-6">
        <div>
          <h2>Qualifications</h2>
          <div class="single-box">
            <h3>Full-Stack Web Developer Bootcamp</h3>
            <p>July - September 2020</p>
            <h4>Le Wagon</h4>
          </div>
          <div class="single-box">
            <h3>Bachelor of International Affairs</h3>
            <p>September 2011 - 2015</p>
            <h4>Saint-Petersburg Institute of International Economic Links, Economics and Law</h4>
          </div>
        </div>
      </div>
    </div><!--#row-->
  </div>
</section><!--#qualifications-->

<section class="fourth-section">
  <div class="container projects">
    <div class="title">
      <h2>Recent Projects</h2>
    </div>
    <div class="row project-row">
      <div class="col-lg-6 col-sm-6 no-padding">
        <img class="debugmom-img img-fluid" src="debug.mom-img.png" alt="DEBUG.mom website picture">
      </div>
      <div class="col-lg-6 col-sm-6 text-inline">
        <h3>DEBUG.mom</h3>
        <p>A team project app created at Le Wagon Bootcamp. 
          It was made for non-tech-savvy people reaching out for help with everyday tech-related problems.
        </p>
        <hr><br>
        <p>
          <a href="http://www.debug-mom.com/" target="_blank"><i class="fas fa-globe"></i> >  Website</a> 
        </p>
        <p>
          <a href="https://github.com/Maxmulis/debug_mom" target="_blank"><i class="fab fa-github"></i> >  GitHub</a>
        </p>
      </div>
    </div><!--#1row-->
    <div class="row project-row">
      <div class="col-lg-6 col-sm-6 text-inline">
        <h3>Flat Tires</h3>
        <p>A team Airbnb clone exercise-project created at Le Wagon Bootcamp. Made in order to exercise programming skills.</p>
        <hr><br> 
        <p>
          <a href="https://flat-tires-platform.herokuapp.com/" target="_blank"><i class="fas fa-globe"></i> >  Website</a> 
        </p>
        <p>
          <a href="https://github.com/ipd39952/flat_tires_platform" target="_blank"><i class="fab fa-github"></i> >  GitHub</a>
        </p>
      </div>
      <div class="col-lg-6 col-sm-6">
        <img class="flatTires-img" src="flatTires-img.png" alt="Flat-Tires website picture">
      </div>
    </div><!--#1row-->
      <div>
        <a class="btn btn-purple" href="<%= projects_path %>">
          <span>More projects here</span>
          <svg width="13px" height="10px" viewBox="0 0 13 10">
            <path d="M1,5 L11,5"></path>
            <polyline points="8 1 12 5 8 9"></polyline>
          </svg>
        </a>
    </div>
  </div>
</section><!--#fourth-section-->

<section class="fifth-section">
  <div class="title">
    <h2>Hobbies</h2>
  </div>
  <div class="container">
    <div class="row hobbies">
      <div class="col-lg-4 col-md-6">
        <div class="feature-item travel-img">
          <p>Traveling is a passion</p>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="feature-item sport-img">
          <p>Sport is a lifestyle</p>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="feature-item video-img">
          <p>Video editing is an entertainment</p>
        </div>
      </div>
    </div>
  </div>
</section><!--#fifth-section-->

app/views/pages/projects.html.erb
<section class="card-palette">
  <main class="page-content">
    <div class="card card-img" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(https://images.unsplash.com/photo-1568775376697-e16970e74861?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1055&q=80)">
      <div class="content">
        <h2 class="title">Flat Tires</h2>
        <p class="copy">A team made Airbnb clone exercise-project made in order to exercise programming skills.</p><hr>
        <a class="btn-sm-purple" href="https://flat-tires-platform.herokuapp.com/" target="_blank">View</a>
      </div>
    </div>
    <div class="card card-img" style="background-image: linear-gradient(rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.2)), url(debug_girl.png)">
      <div class="content">
        <h2 class="title">DEBUG.mom</h2>
        <p class="copy">A team made app for non-tech-savvy people reaching out for help with everyday tech-related problems.</p>
        <a class="btn-sm-purple" href="http://www.debug-mom.com/" target="_blank">View</a>
      </div>
    </div>
    <div id="form-project" class="card card-img" style="background-image: linear-gradient(rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.2)), url(images/survey-img.png)">
      <div class="content">
        <h2 class="title">Survey Form</h2>
        <p class="copy">Survey form made using Bootstrap & SASS.</p> <hr><hr>
        <a class="btn-sm-purple" href="https://codepen.io/1Kris1/full/rNMxqdP" target="_blank">View</a>
      </div>
    </div>
    <div id="form-project" class="card card-img" style="background-image: linear-gradient(rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.2)), url(images/product-page.png)">
      <div class="content">
        <h2 class="title">Product Landing Page</h2>
        <p class="copy">Responsive Product Landing Page made using SASS and Grid system.</p>
        <a class="btn-sm-purple" href="https://codepen.io/1Kris1/full/gOwMppY" target="_blank">View</a>
      </div>
    </div>
    <div class="card">
      <div class="content">
        <h2 class="title">Upcoming project</h2>
        <p class="copy"></p>
        <button class="btn-sm-purple">View</button>
      </div>
    </div>
  </main>
</section><!--#card-palette-->

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    <p>Copyright <i class="fa fa-copyright" aria-hidden="true"></i> 2020 <br>
    Made with <i class="fas fa-heart" ></i> by Kristina Zhizherina</p>
  </div>
   
  <div class="social-links">
  <p> Follow me on </p>
    <ul>
      <li><a href="https://www.linkedin.com/in/kristina-zhizherina-8392631a5/" target="_blank"><i class="fab fa-linkedin"></i></a></li>
      <li><a href="https://github.com/Kristy1max" target="_blank"><i class="fab fa-github-alt"></i></a></li>
      <li><a href="https://www.instagram.com/kris.chouquette/" target="_blank"><i class="fab fa-instagram"></i></a></li>
    </ul>
  </div>
</div><!--#footer-->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light nav">
  <a class="navbar-brand" href="<%= home_path %>">
    <img class="nav-img" src="images/kz-logo.png" alt="Navbar image" copyright="Icon made by Flat Icons from Darius Dan">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= home_path %>">Home</a>
        <a class="nav-link" href="<%= projects_path %>">Projects</a>
      </li>
    </ul>
  </div>
</div>